namespace VideoContactSheet.Test;

public class ContactSheetRenderTests
{
    [Fact]
    public void Render_TextFreeSheet_HasExpectedDimensionsAndPixels()
    {
        var options = TextFreeOptions();
        var thumbnails = TestFrames.Grid(8); // eight 160x90 frames over 4 columns

        try
        {
            var bytes = new ContactSheet(options).Render(thumbnails);
            using var decoded = SKBitmap.Decode(bytes);

            // width = 4*160 + 5*2 ; height = 2 rows of (90 + 2) + 2
            Assert.Equal(650, decoded.Width);
            Assert.Equal(186, decoded.Height);

            // Top-left gutter is the sheet background; first thumbnail centre is palette[0].
            Assert.Equal(options.SheetBackground, decoded.GetPixel(0, 0));
            Assert.Equal(TestFrames.Palette[0], decoded.GetPixel(82, 47));
        }
        finally
        {
            TestFrames.DisposeAll(thumbnails);
        }
    }

    [Fact]
    public async Task Render_TextFreeSheet_MatchesSnapshot()
    {
        var thumbnails = TestFrames.Grid(8);

        try
        {
            var bytes = new ContactSheet(TextFreeOptions()).Render(thumbnails);
            await Verify(bytes, "png");
        }
        finally
        {
            TestFrames.DisposeAll(thumbnails);
        }
    }

    [Fact]
    public void Render_WithSignature_FooterBandReachesBottomEdge()
    {
        var options = TextFreeOptions();
        options.ShowSignature = true; // footer slate band must reach the ceil-rounded bottom row
        var thumbnails = TestFrames.Grid(8);

        try
        {
            var bytes = new ContactSheet(options).Render(thumbnails);
            using var decoded = SKBitmap.Decode(bytes);

            // Bottom-left carries no text, so it must be the footer background, not a white sliver.
            Assert.NotEqual(options.SheetBackground, options.SignatureStyle.Background);
            Assert.Equal(options.SignatureStyle.Background, decoded.GetPixel(0, decoded.Height - 1));
        }
        finally
        {
            TestFrames.DisposeAll(thumbnails);
        }
    }

    [Fact]
    public void Render_Signature_IsHorizontallyCentered()
    {
        var options = TextFreeOptions();
        options.ShowSignature = true;
        options.Signature = "Generated by VideoContactSheet";
        var thumbnails = TestFrames.Grid(8);

        try
        {
            var bytes = new ContactSheet(options).Render(thumbnails);
            using var decoded = SKBitmap.Decode(bytes);

            // Find the horizontal ink extent of the footer text (black on slate, bottom band only).
            int minX = int.MaxValue;
            int maxX = -1;
            for (int y = Math.Max(0, decoded.Height - 20); y < decoded.Height; y++)
            {
                for (int x = 0; x < decoded.Width; x++)
                {
                    var p = decoded.GetPixel(x, y);
                    if (p.Red < 80 && p.Green < 80 && p.Blue < 80)
                    {
                        minX = Math.Min(minX, x);
                        maxX = Math.Max(maxX, x);
                    }
                }
            }

            Assert.True(maxX > minX, "expected footer text ink in the bottom band");

            // Centered text's ink midpoint sits at the image centre; right-aligned would sit far right.
            float inkCentre = (minX + maxX) / 2f;
            Assert.InRange(inkCentre, (decoded.Width / 2f) - 5, (decoded.Width / 2f) + 5);
        }
        finally
        {
            TestFrames.DisposeAll(thumbnails);
        }
    }

    [Fact]
    public void Render_WithShadows_HasSymmetricOuterMargins()
    {
        var options = new ContactSheetOptions
        {
            Columns = 3,
            Rows = 2,
            Padding = 4,
            SoftShadow = true,
            ShadowSize = 6,
            Polaroid = false,
            Timestamp = false,
            ShowHeader = false,
            ShowSignature = false,
            Title = null,
        };
        var thumbnails = TestFrames.Grid(6, 120, 68);

        try
        {
            var bytes = new ContactSheet(options).Render(thumbnails);
            using var decoded = SKBitmap.Decode(bytes);

            // Bounding box of the vivid thumbnail pixels (white background and grey shadows have
            // near-zero saturation, so they're excluded — only the colour frames count).
            int minX = int.MaxValue;
            int maxX = -1;
            int minY = int.MaxValue;
            int maxY = -1;
            for (int yy = 0; yy < decoded.Height; yy++)
            {
                for (int xx = 0; xx < decoded.Width; xx++)
                {
                    var p = decoded.GetPixel(xx, yy);
                    int saturation = Math.Max(p.Red, Math.Max(p.Green, p.Blue)) - Math.Min(p.Red, Math.Min(p.Green, p.Blue));
                    if (saturation > 60)
                    {
                        minX = Math.Min(minX, xx);
                        maxX = Math.Max(maxX, xx);
                        minY = Math.Min(minY, yy);
                        maxY = Math.Max(maxY, yy);
                    }
                }
            }

            int leftMargin = minX;
            int rightMargin = decoded.Width - 1 - maxX;
            int topMargin = minY;
            int bottomMargin = decoded.Height - 1 - maxY;

            Assert.InRange(Math.Abs(leftMargin - rightMargin), 0, 1);
            Assert.InRange(Math.Abs(topMargin - bottomMargin), 0, 1);
        }
        finally
        {
            TestFrames.DisposeAll(thumbnails);
        }
    }

    [Fact]
    public void Render_WithShadows_KeepsInterThumbnailGapEqualToPadding()
    {
        var options = new ContactSheetOptions
        {
            Columns = 3,
            Rows = 1,
            Padding = 4,
            SoftShadow = true,
            ShadowSize = 6,
            Polaroid = false,
            Timestamp = false,
            ShowHeader = false,
            ShowSignature = false,
            Title = null,
        };
        var thumbnails = TestFrames.Grid(3, 120, 68);

        try
        {
            var bytes = new ContactSheet(options).Render(thumbnails);
            using var decoded = SKBitmap.Decode(bytes);

            // Scan a line through the row and collect the vivid (thumbnail) runs.
            int scanY = options.Padding + options.ShadowSize + 34;
            var runs = new List<(int Start, int End)>();
            int runStart = -1;
            for (int x = 0; x < decoded.Width; x++)
            {
                var p = decoded.GetPixel(x, scanY);
                bool vivid = Math.Max(p.Red, Math.Max(p.Green, p.Blue)) - Math.Min(p.Red, Math.Min(p.Green, p.Blue)) > 60;
                if (vivid && runStart < 0)
                {
                    runStart = x;
                }
                else if (!vivid && runStart >= 0)
                {
                    runs.Add((runStart, x - 1));
                    runStart = -1;
                }
            }

            Assert.Equal(3, runs.Count);

            // The gap between adjacent thumbnails must be just `padding` — not `padding + shadow`.
            for (int i = 1; i < runs.Count; i++)
            {
                int gap = runs[i].Start - runs[i - 1].End - 1;
                Assert.InRange(gap, options.Padding - 1, options.Padding + 1);
            }
        }
        finally
        {
            TestFrames.DisposeAll(thumbnails);
        }
    }

    // Text-free so the snapshot is portable: no fonts (the one cross-machine variable) participate.
    private static ContactSheetOptions TextFreeOptions() => new()
    {
        Columns = 4,
        Padding = 2,
        SoftShadow = false,
        Polaroid = false,
        Timestamp = false,
        ShowHeader = false,
        ShowSignature = false,
        Title = null,
    };
}
