using SkiaSharp;

namespace VideoContactSheet;

/// <summary>Styling for a single text region (header, title, timestamp, signature).</summary>
public sealed class ContactSheetOptions
{
    // ---- Grid ----
    public int Columns { get; set; } = 4;

    public int Rows { get; set; } = 4;

    /// <summary>If set, frames are taken at this interval and rows are derived (overrides Rows).</summary>
    public TimeIndex? Interval { get; set; }

    public int Padding { get; set; } = 2;

    public int ThumbnailWidth { get; set; } = 320;

    // ---- Range ----
    public TimeIndex? From { get; set; }

    public TimeIndex? To { get; set; }

    // ---- Output ----
    public SheetFormat Format { get; set; } = SheetFormat.Png;

    public int JpegQuality { get; set; } = 95;

    // ---- Text / metadata ----
    public string? Title { get; set; }

    public string? Signature { get; set; } = "Generated by VideoContactSheet";

    public bool ShowSignature { get; set; } = true;

    public bool ShowHeader { get; set; } = true;

    // ---- Filters ----
    public bool Timestamp { get; set; } = true;

    public bool Polaroid { get; set; }

    public bool SoftShadow { get; set; } = true;

    public int ShadowSize { get; set; } = 6;

    // ---- Highlights (extra frames inserted at the top) ----
    public List<TimeIndex> Highlights { get; } = new();

    // ---- Blank-frame evasion ----
    public bool BlankEvasion { get; set; } = true;

    public double BlankThreshold { get; set; } = 0.08;

    public IReadOnlyList<int> BlankAlternatives { get; set; } = [-5, 5, -10, 10, -30, 30, 0];

    // ---- Colors ----
    public SKColor SheetBackground { get; set; } = SKColors.White;

    public SKColor HighlightBackground { get; set; } = new(0x70, 0x80, 0x90);

    // ---- Styles ----
    public TextStyle HeaderStyle { get; set; } = new()
    {
        Size = 14,
        Color = SKColors.Black,
        Background = new SKColor(0xaf, 0xcd, 0x7a),
    };

    public TextStyle TitleStyle { get; set; } = new()
    {
        Size = 33,
        Color = SKColors.Black,
        Background = SKColors.White,
        Bold = true,
    };

    public TextStyle TimestampStyle { get; set; } = new()
    {
        Size = 14,
        Color = SKColors.White,
        Background = new SKColor(0x00, 0x00, 0x00, 0xaa),
    };

    public TextStyle SignatureStyle { get; set; } = new()
    {
        Size = 10,
        Color = SKColors.Black,
        Background = new SKColor(0x70, 0x80, 0x90),
    };
}

/// <summary>Styling for a single text region (header, title, timestamp, signature).</summary>
public sealed class TextStyle
{
    public string? FontFamily { get; set; }

    public string? FontFile { get; set; }

    public float Size { get; set; } = 14;

    public SKColor Color { get; set; } = SKColors.Black;

    public SKColor Background { get; set; } = SKColors.Transparent;

    public bool Bold { get; set; }

    public TextStyle Clone() => (TextStyle)MemberwiseClone();
}
